version: '2'
services:

##### NODEJS ##################################################################################
  nodejs:
    links:
      - database
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    volumes:
      - ./nodejs:/home/app/api
      - /home/app/api/node_modules
    networks:
      - nodejs


##### DATABASE ##################################################################################
  database:
    image: sameersbn/mysql
    volumes:
      - "./mysql:/var/lib/mysql"
    networks:
      - nodejs

networks:
  nodejs:
