version: '2'
services:

##### NODEJS ##################################################################################
  nodejs:
    links:
      - database
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    volumes:
      - ./nodejs:/home/app/api
      - /home/app/api/node_modules
    environment:
      - EM_DB_USER=${EM_DB_USER}
      - EM_DB_PASS=${EM_DB_PASS}
      - EM_DB_HOST=${EM_DB_HOST}
      - EM_LOGGLY_TOKEN=${EM_LOGGLY_TOKEN}
      - EM_LOGGLY_SUBDOMAIN=${EM_LOGGLY_SUBDOMAIN}
      - EM_LOG_LEVEL=${EM_LOG_LEVEL}
    networks:
      - nodejs


##### DATABASE ##################################################################################
  database:
    image: sameersbn/mysql
    volumes:
      - "./mysql:/var/lib/mysql"
    networks:
      - nodejs

networks:
  nodejs:
